version: '3'

services:
  server:
    image: drone/drone:1
    env_file: SERVER.env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/drone:/data"
  agent:
    image: drone/agent:1
    env_file: AGENT.env
    restart: always
    depends_on: 
      - server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

