elasticsearch:
  image: elasticsearch:latest
  ports:
    - 9200:9200
    - 9300:9300
  environment:
    ES_JAVA_OPTS: "-Xms1g -Xmx1g"

kibana:
  image: kibana:latest
  links:
    - elasticsearch
  ports:
    - 0.0.0.0:5601:5601
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

logstash:
  image: logstash:latest
  entrypoint: logstash -f /etc/logstash/conf.d/logstash.conf
  links:
    - elasticsearch
  ports:
    - 0.0.0.0:5000:5000
  volumes:
    - ${PWD}/logstash:/etc/logstash/conf.d
