apiVersion: 1

datasources:
  - name: telegraf 
    type: influxdb
    access: proxy
    database: telegraf
    user: grafana
    url: http://influxdb:8086
    jsonData:
      timeInterval: "10s"
    secureJsonData:
      password: grafana


